# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='task_content',
            field=models.CharField(default='YourTask', max_length=1024),
        ),
    ]
