# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_donetaskmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskmodel',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.RenameField(
            model_name='donetaskmodel',
            old_name='check_list',
            new_name='checkbox',
        ),
        migrations.RenameField(
            model_name='taskmodel',
            old_name='check_list',
            new_name='checkbox',
        ),
    ]
