# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20160722_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compltaskmodel',
            options={'verbose_name': 'Completed Task', 'verbose_name_plural': 'Completed Tasks'},
        ),
        migrations.AlterField(
            model_name='compltaskmodel',
            name='c_task_content',
            field=models.CharField(default='ComplTask', max_length=256),
        ),
    ]
